apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mq
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    path: /share/trymq
    server: 9.121.242.198
