apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mq-dev
  namespace: hcl-mq
  labels:
    app: mq-dev
spec:
  serviceName: mq-dev
  replicas: 1
  selector:
    matchLabels:
       app: mq-dev
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mq-dev
    spec:
      containers:
      - name: qmgr
        image: myclusterhcl1.icp:8500/hcl-mq/mqtest:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 1414
        env:
        - name: LICENSE
          value: "accept"
        - name: MQ_ADMIN_PASSWORD
          value: "passw0rd"
        - name: MQ_QMGR_NAME
          value: "QM1"		
        volumeMounts:
        - name: vol
          mountPath: /mnt/mqm
        resources:
          limits:
            cpu: 1.0
            memory: 512Mi
          requests:
            cpu: 0.5
            memory: 256Mi
  volumeClaimTemplates:
  - metadata:
      name: vol
      labels:
        app: mq-dev
    spec:
      storageClassName: ""
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi      
---
apiVersion: v1
kind: Service
metadata:
  name: mq-dev 
  namespace: hcl-mq
  labels:
    app: mq-dev
spec:
  type: NodePort 
  ports:
  - port: 9443
    name: console-https
  - port: 1414
    name: qmgr
  selector:
    app: mq-dev
	
